import { createRouter, createWebHashHistory, createWebHistory } from 'vue-router'

import { useAuthStore, usePermissionStore, useUserStore } from '@/store'
import { setupRouterGuard } from './guard'

import { basicRoutes } from './routes'

export const router = createRouter({
  // 静态托管（如 GitHub Pages）下直接访问子路径会 404, 故 mock 构建走 hash 路由
  history: import.meta.env.VITE_USE_HASH_ROUTER === 'true'
    ? createWebHashHistory()
    : createWebHistory(import.meta.env.VITE_PUBLIC_PATH), // '/admin'
  routes: basicRoutes,
  scrollBehavior: () => ({ left: 0, top: 0 }),
})

/**
 * Initialize router
 */
export async function setupRouter(app) {
  await addDynamicRoutes()
  setupRouterGuard(router)
  app.use(router)
}

/**
 * ! Add dynamic routes: generated by frontend or backend based on config
 */
export async function addDynamicRoutes() {
  const authStore = useAuthStore()

  if (!authStore.token) {
    authStore.toLogin()
    return
  }

  // When token exists
  try {
    const userStore = useUserStore()
    const permissionStore = usePermissionStore()

    // If userId does not exist, fetch user info using token
    if (!userStore.userId) {
      await userStore.getUserInfo()
    }

    // Determine whether to generate routes on frontend or backend based on env
    const accessRoutes = JSON.parse(import.meta.env.VITE_BACK_ROUTER)
      ? await permissionStore.generateRoutesBack()
      : permissionStore.generateRoutesFront(['admin'])

    // Check for duplicate route names and add routes
    const addedNames = new Set()

    const addRoute = (route) => {
      let routeName = route.name

      // Handle duplicate route names
      if (addedNames.has(routeName) || router.hasRoute(routeName)) {
        routeName = `${routeName}-${Date.now()}`
        route.name = routeName
      }

      addedNames.add(routeName)

      try {
        router.addRoute(route)
      }
      catch (e) {
        console.warn(`添加路由 ${routeName} 失败:`, e.message)
      }
    }

    // Add routes
    accessRoutes.forEach(addRoute)
  }
  catch (err) {
    console.error('addDynamicRoutes Error: ', err)
  }
}

/**
 * Reset router
 */
export async function resetRouter() {
  router.getRoutes().forEach((route) => {
    const name = route.name
    if (!basicRoutes.some(e => e.name === name) && router.hasRoute(name)) {
      router.removeRoute(name)
    }
  })
}
